// 10 — Mobile viewport: bottom nav replaces sidebar, views switch.
import { test, expect } from '@playwright/test';
import { gotoApp, skipIntro, createWallet , appClick, openView} from './helpers.js';

test.use({ viewport: { width: 390, height: 844 } });

test.describe('Mobile', () => {
  test('mobile nav visible, sidebar hidden', async ({ page }) => {
    await gotoApp(page);
    await skipIntro(page);
    await createWallet(page);
    await expect(page.locator('#mobileNav')).toBeVisible();
    await expect(page.locator('.sidebar')).toBeHidden();
  });

  // The bar is generated by syncMobileNav() from the sidebar: 4 primary tabs
  // (dashboard, swap, activity, nft) plus a More button that opens a sheet with
  // every remaining view. Settings used to be a direct bar item; it now lives
  // behind More, so both routes are asserted here.
  test('mobile nav switches views', async ({ page }) => {
    await gotoApp(page);
    await skipIntro(page);
    await createWallet(page);
    for (const v of ['activity', 'swap', 'dashboard']) {
      await appClick(page, `.mobile-nav-item[data-view="${v}"]`);
      await expect(page.locator('#view-' + v), `#view-${v} must activate`).toHaveClass(/active/);
    }
    // The bar is five fixed slots, in this order, and there is no More button.
    const slots = await page.locator('#mobileNav .mobile-nav-item').evaluateAll((els) =>
      els.map((e) => e.dataset.view || '(none)'));
    expect(slots).toEqual(['dashboard', 'activity', 'swap', 'dapps', 'settings']);
    await expect(page.locator('#mobileMoreBtn')).toHaveCount(0);
    await expect(page.locator('#navSheet')).toHaveCount(0);
    // A slot lights up for its own view and nothing lights up for a view that
    // is reached from the Dashboard or from Settings — the bar is not broken,
    // that view simply is not one of the five.
    await appClick(page, '#mobileNav .mobile-nav-item[data-view="settings"]');
    await expect(page.locator('#view-settings')).toHaveClass(/active/);
    await expect(page.locator('#mobileNav .mobile-nav-item[data-view="settings"]')).toHaveClass(/active/);
    await openView(page, 'approval');
    await expect(page.locator('#view-approval')).toHaveClass(/active/);
    await expect(page.locator('#mobileNav .mobile-nav-item.active')).toHaveCount(0);
  });

  test('mobile swap second tap opens chooser → bridge', async ({ page }) => {
    await gotoApp(page);
    await skipIntro(page);
    await createWallet(page);
    await appClick(page, '.mobile-nav-item[data-view="swap"]');
    await appClick(page, '.mobile-nav-item[data-view="swap"]');
    await expect(page.locator('#chooseBridge')).toBeVisible();
    await appClick(page, '#chooseBridge');
    await expect(page.locator('#view-bridge')).toHaveClass(/active/);
  });

  test('mobile quick actions work', async ({ page }) => {
    await gotoApp(page);
    await skipIntro(page);
    await createWallet(page);
    await appClick(page, '.quick-action-btn[data-view="send"]');
    await expect(page.locator('#view-send')).toHaveClass(/active/);
  });
});