// 10 — Mobile viewport: bottom nav replaces sidebar, views switch.
import { test, expect } from '@playwright/test';
import { gotoApp, skipIntro, createWallet , appClick} from './helpers.js';

test.use({ viewport: { width: 390, height: 844 } });

test.describe('Mobile', () => {
  test('mobile nav visible, sidebar hidden', async ({ page }) => {
    await gotoApp(page);
    await skipIntro(page);
    await createWallet(page);
    await expect(page.locator('#mobileNav')).toBeVisible();
    await expect(page.locator('.sidebar')).toBeHidden();
  });

  // The bar is generated by syncMobileNav() from the sidebar: 4 primary tabs
  // (dashboard, swap, activity, nft) plus a More button that opens a sheet with
  // every remaining view. Settings used to be a direct bar item; it now lives
  // behind More, so both routes are asserted here.
  test('mobile nav switches views', async ({ page }) => {
    await gotoApp(page);
    await skipIntro(page);
    await createWallet(page);
    for (const v of ['activity', 'swap', 'dashboard']) {
      await appClick(page, `.mobile-nav-item[data-view="${v}"]`);
      await expect(page.locator('#view-' + v), `#view-${v} must activate`).toHaveClass(/active/);
    }
    // Settings is not a bar item any more — reach it through the More sheet.
    await expect(page.locator('#mobileNav .mobile-nav-item[data-view="settings"]')).toHaveCount(0);
    await appClick(page, '#mobileMoreBtn');
    await page.waitForSelector('#navSheet', { timeout: 10_000 });
    await appClick(page, '#navSheet .nav-sheet-item[data-view="settings"]');
    await expect(page.locator('#view-settings')).toHaveClass(/active/);
    // A view behind More has no bar button, so More itself carries the active state.
    await expect(page.locator('#mobileMoreBtn')).toHaveClass(/active/);
  });

  test('mobile swap second tap opens chooser → bridge', async ({ page }) => {
    await gotoApp(page);
    await skipIntro(page);
    await createWallet(page);
    await appClick(page, '.mobile-nav-item[data-view="swap"]');
    await appClick(page, '.mobile-nav-item[data-view="swap"]');
    await expect(page.locator('#chooseBridge')).toBeVisible();
    await appClick(page, '#chooseBridge');
    await expect(page.locator('#view-bridge')).toHaveClass(/active/);
  });

  test('mobile quick actions work', async ({ page }) => {
    await gotoApp(page);
    await skipIntro(page);
    await createWallet(page);
    await appClick(page, '.quick-action-btn[data-view="send"]');
    await expect(page.locator('#view-send')).toHaveClass(/active/);
  });
});